import os


SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URI')
SQLALCHEMY_TRACK_MODIFICATIONS = False


WHATSAPP_TOKEN = "THE_TOKEN_HERE"
PHONE_NUMBER_ID = "PHONE_NUMBER_ID"


AI_API_KEY = "AI_API_KEY"