import os

from dotenv import load_dotenv

load_dotenv()

SQLALCHEMY_DATABASE_URI = os.getenv("SQLALCHEMY_DATABASE_URI")
SQLALCHEMY_TRACK_MODIFICATIONS = False


WHATSAPP_TOKEN = "THE_TOKEN_HERE"
PHONE_NUMBER_ID = "PHONE_NUMBER_ID"


AI_API_KEY = "AI_API_KEY"